# Docker-compose to create Elixir development container that connects to a PostgreSQL container.
# reference: https://pspdfkit.com/blog/2018/how-to-run-your-phoenix-application-with-docker/

version: '3.8'

services:
  # Elixir container
  elixir:
    build:
      context: .
    environment:
      # Variables to connect to our PostgreSQL server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: deliverycenter_elixir
      PGPORT: 5432
      PGHOST: db
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      - db
  
  # PostgreSQL container
  db:
    image: postgres:9.6
    environment:
      # Set user/password for PostgreSQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define the volumes
volumes:
  pgdata: